### ISSUE TITLE
imaplibutil.py does not import fcntl

### ISSUE THREAD

**Issue by shivapd** [OfflineIMAP/offlineimap3#115]
#### General informations

- system/distribution (with version): macOS 12.2.1
- offlineimap version (`offlineimap -V`): offlineimap v8.0.0, imaplib2 v3.06, Python v3.9.12, OpenSSL 1.1.1n  15 Mar 2022
- Python version: 3.9
- server name or domain: 
- CLI options: 

#### Configuration file offlineimaprc

```
[general]
accounts = <snip>
ui = basic

[Account <snip>]
localrepository = Local
remoterepository = Remote
autorefresh = 3
quick = 10

[Repository Local]
type = Maildir
localfolders = ~/Mail




[Repository Remote]
type = IMAP
remotehost = <snip>
remoteuser = <snip>
preauthtunnel = ssh -q <snip> '/usr/lib/dovecot/imap'
```

#### Logs, error

```
ERROR: While attempting to sync account '<snip>'
  name 'fcntl' is not defined
```

#### Steps to reproduce the error

- Run offlineimap.
- 

I added "import fcntl" to imaplibutil.py and the issue went away.

**Comment by huyz** [comment]
Oh nice.  I've been sticking with 7.3.4 (and python2) precisely because of this issue.  I'll wait until 8.0.1 with this fix to upgrade

**Comment by sudipm-mukherjee** [comment]
@thekix  This issue seems to be same as https://bugs.debian.org/1057921 but the bug report says that this started with the last upgrade to `git20231201.77e70ed`.

**Comment by etbuira** [comment]
Hi,
@shivapd if the merged PR fixes things for you, please close this issue.
Regards

**Comment by thekix** [comment]
This issue should be solved. Please reopen it if the problem continues.
