### ISSUE TITLE
Feture Request: Support reading password from stdout

### ISSUE THREAD

**Issue by danisztls** [OfflineIMAP/offlineimap3#125]
## Rationality
A CLI password manager like [gopass](https://github.com/gopasspw/gopass) can safely store a password and output it to stdout when invoked.

Example of usage:

```shell
> gopass show imap_account
my_password
```

This would be a nice alternative to storing the `remotepass` as plaintext.

**Comment by etbuira** [comment]
Hi,
It should already do so, but these days, you might need to call it with --ignore-keyring argument, or in your config's [general] section.
Please close if it fix things for you.

**Comment by danisztls** [comment]
It appears this is possible via `remotepasseval`. https://github.com/OfflineIMAP/offlineimap/blob/ffbace51a265fea6a1d50a92cba4e776f03f705e/offlineimap.conf#L1018
