### ISSUE TITLE
v8.0.0 requirements

### ISSUE THREAD

**Issue by nameduser0** [OfflineIMAP/offlineimap3#127]
v8.0.0 needs the `distro` and `imaplib2` packages
distro seems to be required by `platform`

#### General informations

- system/distribution (with version): Debian 11
- offlineimap version (`offlineimap -V`): 8.0.0
- Python version: 3.9.2

#### Steps to reproduce the error

- `./env/bin/python -m pip install -v git+https://github.com/offlineIMAP/offlineimap3.git@v8.0.0`

Ref:
https://github.com/OfflineIMAP/offlineimap3/issues/100

**Comment by wosc** [comment]
As far as I can tell, the dependencies currently have to be installed explicitly (see e.g. #79), like so:
```
python -m venv env
./env/bin/python -m pip install -r https://raw.githubusercontent.com/OfflineIMAP/offlineimap3/v8.0.0/requirements.txt
./env/bin/python -m pip install git+https://github.com/offlineIMAP/offlineimap3.git@v8.0.0
```
