### ISSUE TITLE
Python 3.11 breaks sqlite multi-threading check

### ISSUE THREAD

**Issue by frabyn** [OfflineIMAP/offlineimap3#136]
Python 3.11 changes the behavior of the sqlite3.threadsafety attribute

https://github.com/python/cpython/issues/89776

The attribute is no longer hard coded to 1 for multi-thread safe and instead is dynamically set at runtime as described here:

https://docs.python.org/3.11/library/sqlite3.html#sqlite3.threadsafety

The call for the attribute here checks only for "1" when multi-threading is now represented by other numbers.

https://github.com/OfflineIMAP/offlineimap3/blob/253f97a3e9476beae837d4d64114fd9698e94498/offlineimap/folder/LocalStatusSQLite.py#L107

The fix may be as easy as this, asserting against single-thread mode rather than asserting for multi-thread or serialized mode:

`
assert sqlite.threadsafety != 0, 'Your sqlite is not multithreading safe.'
`

#### General informations

- system/distribution (with version): Fedora 37 pre-release
- offlineimap version (`offlineimap -V`): offlineimap v8.0.0
- Python version: Python v3.11.0rc1
- CLI options: none

#### Logs, error

```
OfflineIMAP 8.0.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v3.06, Python v3.11.0rc1, OpenSSL 3.0.5 5 Jul 2022
Account sync Fastmail:
 *** Processing account Fastmail
 Establishing connection to imaps-proxy.fastmail.com:80 (FastmailRemote)
 Creating folder Sent[FastmailLocal]
 ERROR: While attempting to sync account 'Fastmail'
  Your sqlite is not multithreading safe.
 *** Finished account 'Fastmail' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: While attempting to sync account 'Fastmail'
  Your sqlite is not multithreading safe.

Traceback:
  File "/usr/lib/python3.11/site-packages/offlineimap/accounts.py", line 298, in syncrunner
    self.__sync()
  File "/usr/lib/python3.11/site-packages/offlineimap/accounts.py", line 377, in __sync
    remoterepos.sync_folder_structure(localrepos, statusrepos)
  File "/usr/lib/python3.11/site-packages/offlineimap/repository/Base.py", line 292, in sync_folder_structure
    status_repo.makefolder(local_name.replace(
  File "/usr/lib/python3.11/site-packages/offlineimap/repository/LocalStatus.py", line 123, in makefolder
    folder.openfiles()
  File "/usr/lib/python3.11/site-packages/offlineimap/folder/LocalStatusSQLite.py", line 107, in openfiles
    assert sqlite.threadsafety == 1, 'Your sqlite is not multithreading safe.'
```

#### Steps to reproduce the error
- Upgrade to Python 3.11
- Run offlineimap

**Comment by ag91** [comment]
experiencing the same and that indeed solves the issue
