### ISSUE TITLE
We should use as default system sslcacertfile?

### ISSUE THREAD

**Issue by thekix** [OfflineIMAP/offlineimap3#14]
After the changes in the patch

https://github.com/OfflineIMAP/offlineimap3/pull/13/commits/fe25a5c7525fe8fa38a1254e14dc5ce75e79a08e

I think is possible to remove the sslcacertfile variable form the .offlineimaprc and use the system's default. This could be easy for new users. The current config is always like:

```
[Repository Remote-gmail]
type = Gmail
ssl = yes
remotehost = imap.gmail.com
remoteport = 993
remoteuser =user
remotepass = verysecurepass1
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
```

With the previouse patch, we can change the file to:

```
[Repository Remote-gmail]
type = Gmail
ssl = yes
remotehost = imap.gmail.com
remoteport = 993
remoteuser =user
remotepass = verysecurepass1
sslcacertfile = OS-DEFAULT
```

But my proposal is no variable, and then offlineimap uses OS-DEFAULT:

```
[Repository Remote-gmail]
type = Gmail
ssl = yes
remotehost = imap.gmail.com
remoteport = 993
remoteuser =user
remotepass = verysecurepass1
```

What do you think?

Regards,
kix

**Comment by nicolas33** [comment]
Interesting. We might like to pick this change in offlineimap to help the transition. The main issue is when no default is provided. I wonder we don't cover all the systems.

There should be a deprecation about this configuration variable if it's used and fallbacks to something more 'offlineimap' like `['<medatadadir>/<ACCOUNT_NAME>/ssl/', '/etc/offlineimap/ssl']` so that no user gets blocked.

**Comment by thekix** [comment]
Hi @nicolas33 

about the main issue. Currently, these are the options:

- User specifies sslacertfile -> OK
- User specifies sslacertfile=OS-DEFAULT
  - If the system's default is provided -> OK
  - If the system's default is not provided -> Fail
- User do not specifies sslacertfile -> Fail
- User specifies empty sslacertfile -> Fail

With the new option (patch below).

- User specifies sslacertfile -> OK
- User specifies sslacertfile=OS-DEFAULT or
  User do not specifies sslacertfile or
  User specifies empty sslacertfile
  - If the system's default is provided -> OK
  - If the system's default is not provided -> Fail

IMO, many new users do not have too much idea about sslacertfile or they need spend time to search it. With this patch, the user do not need include the file. If the system's default is not provided, the user can specifies their file.

We can also use a list of defaults and test every default to find the sslacert (now, we have an iterable, not only one file).

Patch:

```
kix@inle:~/src/offlineimap3$ git diff
diff --git a/offlineimap/repository/IMAP.py b/offlineimap/repository/IMAP.py
index a6c330e..68f1800 100644
--- a/offlineimap/repository/IMAP.py
+++ b/offlineimap/repository/IMAP.py
@@ -233,13 +233,15 @@ class IMAPRepository(BaseRepository):
     def getsslcacertfile(self):
         """Determines CA bundle.
 
-        Returns path to the CA bundle.  It is either explicitely specified
-        or requested via "OS-DEFAULT" value (and we will search known
-        locations for the current OS and distribution).
+        Returns path to the CA bundle.  It is explicitely specified or
+        requested via "OS-DEFAULT" value (and we will search known
+        locations for the current OS and distribution). If it is not
+        specified, we will search it in the known locations.
 
-        If search via "OS-DEFAULT" route yields nothing, we will throw an
-        exception to make our callers distinguish between not specified
-        value and non-existent default CA bundle.
+        If search route, via "OS-DEFAULT" or because is not specified,
+        yields nothing, we will throw an exception to make our callers
+        distinguish between not specified value and non-existent
+        default CA bundle.
 
         It is also an error to specify non-existent file via configuration:
         it will error out later, but, perhaps, with less verbose explanation,
@@ -250,7 +252,10 @@ class IMAPRepository(BaseRepository):
         xforms = [os.path.expanduser, os.path.expandvars, os.path.abspath]
         cacertfile = self.getconf_xform('sslcacertfile', xforms, None)
         # Can't use above cacertfile because of abspath.
-        if self.getconf('sslcacertfile', None) == "OS-DEFAULT":
+        conf_sslacertfile = self.getconf('sslcacertfile', None)
+        if conf_sslacertfile == "OS-DEFAULT" or \
+            conf_sslacertfile == None or \
+            conf_sslacertfile == '':
             cacertfile = get_os_sslcertfile()
             if cacertfile is None:
                 searchpath = get_os_sslcertfile_searchpath()
kix@inle:~/src/offlineimap3$
```

**Comment by nicolas33** [comment]
That's great!

**Comment by thekix** [comment]
Thanks @nicolas33 :-)

Probably you can apply this patch to offlineimap (py2)

Regards,
kix
