### ISSUE TITLE
Question: Is anyone successful in setting up offlineimap to use office 365 oauth2?

### ISSUE THREAD

**Issue by noorul** [OfflineIMAP/offlineimap3#147]
Is anyone successful in setting up offlineimap to use Office 365 oauth2 ?

**Comment by glennmorris** [comment]
Works for me, using a technique based on https://github.com/UvA-FNWI/M365-IMAP

**Comment by noorul** [comment]
I was also using the same. But it no longer works as the secret no longer works. It looks like thunderbird moved to a different approach.

**Comment by chris001** [comment]
Thunderbird has changed its app client ID/secret for Microsoft login.  The new app uses `https` only!

You could try to use [this one](https://github.com/2e0byo/email) until M365-IMAP gets updated, it's a fork of M365-IMAP, with the new Thunderbird app client ID/secret, and uses the `https` required for login redirect.

**Comment by noorul** [comment]
@chris001 Even though using it was not straight forward, it worked. Thanks a ton @chris001

**Comment by chris001** [comment]
@noorul If you could, share your step-by-step commands and config file edits, for how you use [that one](https://github.com/2e0byo/email) to use office 365 `oauth2`, to help other users?
