### ISSUE TITLE
Why does the readme recommend an AUR package?

### ISSUE THREAD

**Issue by metov** [OfflineIMAP/offlineimap3#153]
The readme says to install the AUR package `offlineimap3-git`. However there is also the Arch package `offlineimap` https://archlinux.org/packages/community/any/offlineimap/. The Arch Wiki also recommends to install `offlineimap`.

What's the deal with this? Is something wrong with the Arch package? Why is the AUR package better?

**Comment by chris001** [comment]
The Arch package was recently created 2 weeks ago, and hasn't been added to readme yet.  It should be just fine to install.

**Comment by chris001** [comment]
@metov [Updated the Readme](https://github.com/OfflineIMAP/offlineimap3#downloads) with Arch package install command.

**Comment by metov** [comment]
Thank you!
