### ISSUE TITLE
Duplicate files appearing

### ISSUE THREAD

**Issue by raboof** [OfflineIMAP/offlineimap3#201]
#### General informations

- system/distribution (with version): NixOS unstable
- offlineimap version (`offlineimap -V`): `offlineimap v8.0.0, imaplib2 v3.06, Python v3.12.4, OpenSSL 3.0.14 4 Jun 2024`
- Python version: 3.12
- server name or domain: custom
- CLI options: none

#### Configuration file offlineimaprc

```
[Account it]
localrepository = it-local
remoterepository = it-remote

[Repository it-local]
type = Maildir
localfolders = ./it

[Repository it-remote]
type = IMAP
remotehost = mail.redacted.nl
remoteuser = it@redacted.nl
sslcacertfile = /etc/ssl/certs/ca-certificates.crt
```

#### Steps to reproduce the error

I was intending to use offlinemap with btrfs filesystem snapshots to make backups of some online IMAP mapboxes to local Maildirs, as alluded to by https://www.offlineimap.org/doc/backups.html . I did a first sync a while ago (end of june), and now did another one.

Unfortunately, it seems this has re-uploaded files that were moved from one folder to another on the IMAP side. Is this expected? The mails are identical (same md5sum in the Maildir, different filename obviously), for example:

```
md5sum "it/INBOX/cur/1722883669_5.274433.rigter,U=923,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S" "it/INBOX.beantwoord/cur/1722883667_4.274433.rigter,U=936,FMD5=ca6144a799c88cb5c5d1917774a59a78:2,S"
440ef945654cc39425388f34602b00ec  it/INBOX/cur/1722883669_5.274433.rigter,U=923,FMD5=7e33429f656f1e6e9d79b29c3f82c57e:2,S
440ef945654cc39425388f34602b00ec  it/INBOX.beantwoord/cur/1722883667_4.274433.rigter,U=936,FMD5=ca6144a799c88cb5c5d1917774a59a78:2,S
```

**Comment by raboof** [comment]
Interestingly, after moving the `INBOX` message 923 to `INBOX.beantwoord` on the IMAP side and syncing again, I saw the following logs:

```
OfflineIMAP 8.0.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v3.06, Python v3.12.4, OpenSSL 3.0.14 4 Jun 2024
Account sync it:
 *** Processing account it
 Establishing connection to mail.eicas.nl:993 (it-remote)
Enter password for user 'it@eicas.nl': 
Folder INBOX [acc: it]:
 Syncing INBOX: IMAP -> Maildir
Folder INBOX.beantwoord [acc: it]:
 Syncing INBOX.beantwoord: IMAP -> Maildir
Folder INBOX [acc: it]:
 Copy message UID 924 (10/10) it-remote:INBOX -> it-local:INBOX
 Copy message UID 923 (1/1) it-local:INBOX -> it-remote:INBOX
Folder INBOX.Drafts [acc: it]:
 Syncing INBOX.Drafts: IMAP -> Maildir
Folder INBOX.INBOX.CiviMail [acc: it]:
 Syncing INBOX.INBOX.CiviMail: IMAP -> Maildir
Folder INBOX.INBOX.CiviMail.ignored [acc: it]:
 Syncing INBOX.INBOX.CiviMail.ignored: IMAP -> Maildir
Folder INBOX.INBOX.CiviMail.processed [acc: it]:
 Syncing INBOX.INBOX.CiviMail.processed: IMAP -> Maildir
Folder INBOX.beantwoord [acc: it]:
 Copy message UID 1039 (104/104) it-remote:INBOX.beantwoord -> it-local:INBOX.beantwoord
```

This suggests message 923 was synced from local to remote, but after this sync neither local or remote have message 923 anymore - but now they both have a message 925 that is a duplicate of it.

**Comment by raboof** [comment]
One other thing: I lost `~/.offlineimap/` between the sync a few weeks ago and the recent sync. I suppose that might have caused the original issue?

I do have access to both the 'old' and the 'new' `~/.offlineimap/`. What would be the best approach to go from here? I guess I can find the duplicate emails based on md5sums and file timestamps, so perhaps I should use that to remove the 'new' duplicates from the local maildirs, sync again, and make sure not to lose `~/.offlineimap` again?

**Comment by etbuira** [comment]
Hi,

I'd say loosing .offlineimap (where some metadata are stored) was not a good idea.
I'd start a fresh sync with a fresh .offlineimap (you can probably rm -r all that in your live fs without touching your old snapshot).

**Comment by raboof** [comment]
> I'd say loosing .offlineimap (where some metadata are stored) was not a good idea.

Clearly :laughing: 

Would it be possible to abort the sync when someone runs offlineimap but ~/.offlineimap is missing while it was expected? That might have saved a lot of headache.

Also, it would be interesting to have a 'one-way'/'read-only' mode? Should I add that as a feature idea in a new issue?

**Comment by etbuira** [comment]
AFAIK, there is no way to stop if .offlineimap is missing, but you can set the path (read example offlineimap.conf), and organise to have all conf, metadata, emails as subdirs of a general dir.

Also, i don't get what you mean by read-only mode, maybe you can be interested in readonly or sync_deletes options (again, in example offlineimap.conf), but that would still need keeping metadata.

**Comment by raboof** [comment]
> AFAIK, there is no way to stop if .offlineimap is missing

Right - that might be a safeguard worth considering. Do you want to keep this issue open for that or shall we close it?

> Also, i don't get what you mean by read-only mode, maybe you can be interested in readonly or sync_deletes options (again, in example offlineimap.conf), but that would still need keeping metadata.

I'm not sure how I missed `readonly`, I did look through the example `offlineimap.conf`... that looks perfect for my use case, thanks!

**Comment by etbuira** [comment]
That issue should probably be closed. I don't know how welcome would be such a safeguard, but that would have more chance if made as a PR (but maintainers are mostly busy elsewhere).

**Comment by raboof** [comment]
OK, thanks a lot for your help!
