### ISSUE TITLE
Remove link to imapfw from homepage

### ISSUE THREAD

**Issue by eyeinsky** [OfflineIMAP/offlineimap3#210]
https://www.offlineimap.org mentions that [imapfw](https://imapfw.offlineimap.org/) is the replacement to offlineimap, while this no longer appears to be the case, so the quote and link can be removed.

**Comment by eyeinsky** [comment]
Created PR https://github.com/OfflineIMAP/offlineimap.github.io/pull/20

**Comment by nicolas33** [comment]
Applied.
