### ISSUE TITLE
Where to get imaplib2 dependency from?

### ISSUE THREAD

**Issue by bkircher** [OfflineIMAP/offlineimap3#35]
Hey there, question:

Where do I get the correct version of imaplib2 from?

I see that there is a version solely used for oflineimap2:
https://github.com/offlineimap/offlineimap3/blob/master/Changelog.md#notes

What version do you use for offlineimap3?

Thanks for the effort here, btw!

**Comment by thekix** [comment]
Hi @bkircher 

Your question is very interesting.

I was using the Debian version of imaplib2 [1]. This version is the upstream imaplib2.py3 version [2] with these patches applied:

- Use SSLContext if available so we send SNI
- Do not use TIMEOUT_MAX for Condition.wait()

These patches are in the "Pull request" for imaplib2.

Now I am using "my own version". Is like the Debian version, with the patch "Remove crash if debug is set and port is not set" (it is in Pull request" too). It only affects an specific problem with debug and tunneling, so is like the Debian version.

If you are using the Debian's version, is perfect. I am not sure about other distros, like Fedora, Slackware,...

Probably, in the future, these patches could be applied to the upstream. See [3].
I proposed migrate imaplib2 to Python 3 standard lib. See [4].

Regards,
kix

[1] Debian version: https://packages.debian.org/sid/python3-imaplib2
[2] Upstream version: https://github.com/imaplib2/imaplib2
[3] https://github.com/imaplib2/imaplib2/issues/7
[4] https://github.com/imaplib2/imaplib2/issues/12

**Comment by bkircher** [comment]
Hey hey @thekix  Many thanks for the thorough answer.

>  [3] imaplib2/imaplib2#7

Upstream is dead it seems. The picture on PyPI looks even more woeful: https://pypi.org/search/?q=imaplib2

FYI, imaplib2 is not packaged for Fedora. At least I couldn't find any.

I'll carry the discussion over to https://github.com/imaplib2/imaplib2/issues/7. Thanks again @thekix
