### ISSUE TITLE
Errors on Windows: fcntl, signal.SIGHUP, OSError is not subscriptable, FileExistsError

### ISSUE THREAD

**Issue by sorcodiv** [OfflineIMAP/offlineimap3#37]
Hi,
I run the last version of offlineimap3 (2021-01-05T08:55:15Z) on windows and had some issues.
Versions: Windows 10, Python 3.9.1 x64; imaplib2 3.06 (last from https://github.com/jazzband/imaplib2); rfc6555-0.0.0, portalocker-2.0.0, selectors2-2.0.2, distro-1.5.0 (from pypi).
offlineimap -V: offlineimap v7.3.0, imaplib2 _v3.06_, Python v3.9.1, OpenSSL 1.1.1g  21 Apr 2020

Run command: offlineimap -o -c test.conf -u Basic
Configuration file test.conf:
> [general]
> metadata = offlineimap.metadata
> maxsyncaccounts = 1
> ui = Basic
> ignore-readonly = no
> accounts = Test
> [Account Test]
> maildir-windows-compatible = yes
> localrepository  = Test_local
> remoterepository = Test_remote
> [Repository Test_local]
> type = Maildir
> localfolders = mail_Test
> [Repository Test_remote]
> sslcacertfile=ca-certificates.crt
> type = IMAP
> ssl = yes
> remotehost = <imap_server>
> remoteuser =
> remotepass =
> subscribedonly = no
> readonly = True

Issues:

1. offlineimap\imaplibutil.py, line 18
ModuleNotFoundError: No module named 'fcntl'
> To continue I just commented all lines with "fcntl".

2. offlineimap\init.py, line 75
info = "imaplib2 v%s, Python v%s" % (`imaplib.__version__`, PYTHON_VERSION)
AttributeError: module 'imaplib2' has no attribute `__version__`
> To continue I replaced `imaplib.__version__` with some string.

3. offlineimap\init.py
ERROR: module 'signal' has no attribute 'SIGHUP' ('SIGUSR1', 'SIGUSR2', 'SIGQUIT')
> To continue I commented lines with "signal.SIGHUP" etc. Like here: https://github.com/hyperopt/hyperopt/pull/452/files/af8ecd2e14e4785517c8be080fa972e5bf539564

4. offlineimap\folder\GmailMaildir.py, line 186, offlineimap\folder\Maildir.py, lines 442, 528
TypeError: 'OSError' object is not subscriptable
> I replaced "e[1]" with "e.errno".

5. offlineimap\folder\Base.py, line 284, and some more files
    os.rename(uidfilename + ".tmp", uidfilename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'offlineimap.metadata\\Repository-Test_local\\FolderValidity\\Drafts.tmp' -> 'offlineimap.metadata\\Repository-Test_local\\FolderValidity\\Drafts'
> This error appear on second run. To work around the error I must remove "offlineimap.metadata" before run offlineimap3.

But in general, I have reached my goal - the letters are downloaded, thanks!

**Comment by thekix** [comment]
Dear @sorcodiv,

thanks a lot for your report. I just upload some patches based on your info. Could you try if now all is fine?

Best Regards,
kix

**Comment by sorcodiv** [comment]
Everything is fine now, thank you very much!
I used commit 896ac98 (2021-08-07) with libraries: [distro-1.6.0](https://github.com/python-distro/distro/releases), [imaplib2-3.6](https://github.com/jazzband/imaplib2/releases), [portalocker-2.3.0](https://github.com/WoLpH/portalocker/releases), [rfc6555-master-2019-09-13](https://github.com/sethmlarson/rfc6555), [selectors2-2.0.2](https://github.com/sethmlarson/selectors2/releases).
