### ISSUE TITLE
Local IMAP server with "snake oil" cert gives error

### ISSUE THREAD

**Issue by diefau** [OfflineIMAP/offlineimap3#38]
#### General informations

- system/distribution (with version): Debian bullseye
- offlineimap version (`offlineimap -V`): offlineimap v7.3.0, imaplib2 v3.05, Python v3.9.1+, OpenSSL 1.1.1i  8 Dec 2020
- Python version: Python 3.9.1+
- server name or domain: a local server
- CLI options: no one (only 'offlineimap')

#### Configuration file offlineimaprc
[general]
metadata = ~/.var/offlineimap
accounts = Test
maxsyncaccounts = 1
ignore-readonly = no

[Account Test]
localrepository = Local-Test
remoterepository = Remote-Test
autorefresh = 10
[Repository Local-Test]
type = IMAP
remotehost = <hostname>
remoteuser = <user>
remotepass = <password>
[Repository Remote-Test]
type = IMAP
remotehost = <server>
remoteuser = <user>
remotepass = <password>
cert_fingerprint = <finger-print>

#### Logs, error
ERROR: Exceptions occurred during the run!
ERROR: Unknown SSL protocol connecting to host '<hostname>' for repository 'Local-Test'. OpenSSL responded:
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1123)

Traceback:
  File "/usr/share/offlineimap3/offlineimap/accounts.py", line 298, in syncrunner
    self.__sync()
  File "/usr/share/offlineimap3/offlineimap/accounts.py", line 375, in __sync
    localrepos.getfolders()
  File "/usr/share/offlineimap3/offlineimap/repository/IMAP.py", line 648, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/share/offlineimap3/offlineimap/imapserver.py", line 662, in acquireconnection
    raise OfflineImapError(reason, severity, exc_info()[2])

#### Steps to reproduce the error
(I think) use a local IMAP server with a self signed certificate

This works well with the old (python2 based) offlineimap

**Comment by vagrantc** [comment]
I also have this issue on Debian bullseye using a self-signed certificate using cert_fingerprint as a minimal defense against MITM attacks, but it breaks in the same way. Previously I used the python2 based offlineimap on Debian buster and that worked fine with such a configuration.

**Comment by diefau** [comment]
I found a workaround for this problem adding this line to the local part:

transporttunnel = openssl s_client -host <hostname> -port 993 -quiet

This works for me but I think it's only a "hack".
