### ISSUE TITLE
Unable to run setup.py from a clean checkout

### ISSUE THREAD

**Issue by offbyone** [OfflineIMAP/offlineimap3#39]
#### General informations

- system/distribution (with version): macOX
- offlineimap version (`offlineimap -V`): N/A
- Python version: 3.8.3
- server name or domain: N/A
- CLI options: N/A

#### Repro steps

```
$ gh repo clone OfflineIMAP/offlineimap3
...
# create a virtualenv for this project here
$ pip freeze
# empty
$ pip install -r requirements.txt
...
$ pip install -r tests/requirements.txt
...
$ pip freeze
attrs==20.3.0
certifi==2020.12.5
chardet==4.0.0
codecov==2.1.11
coverage==5.3.1
decorator==4.4.2
distro==1.5.0
gssapi==1.6.12
idna==2.10
iniconfig==1.1.1
packaging==20.8
pluggy==0.13.1
portalocker==2.1.0
py==1.10.0
pyparsing==2.4.7
pytest==6.2.1
pytest-cov==2.11.1
requests==2.25.1
rfc6555==0.0.0
selectors2==2.0.2
toml==0.10.2
urllib3==1.26.2
$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    import offlineimap
  File "/Users/offby1/projects/offlineimap3/offlineimap/__init__.py", line 20, in <module>
    from offlineimap.init import OfflineImap
  File "/Users/offby1/projects/offlineimap3/offlineimap/init.py", line 29, in <module>
    import imaplib2 as imaplib
ModuleNotFoundError: No module named 'imaplib2'
```

So, uh, how do I get started here? I'm interested in contributing, but it seems that there's something just missing here. My first impulse was to install imaplib2, but that gives me an error that clearly indicates that imaplib2 doesn't support Python 3:

```
$ pip install imaplib2
...
$ python setup.py build
...
  File "/Users/offby1/projects/offlineimap3/offlineimap/imaplibutil.py", line 30, in <module>
    from imaplib2 import IMAP4, IMAP4_SSL, InternalDate
ImportError: cannot import name 'IMAP4' from 'imaplib2' (/Users/offby1/projects/offlineimap3/.direnv/python-3.8.3/lib/python3.8/site-packages/imaplib2/__init__.py)
```

And trying to install the version that is called out in the README is not possible:

```
$ pip install 'imaplib2>=3.5'
Collecting imaplib2>=3.5
  ERROR: Could not find a version that satisfies the requirement imaplib2>=3.5 (from versions: 2.28.1, 2.28.2, 2.28.3, 2.37.4, 2.38.0, 2.43.0, 2.45.0)
```

**Comment by offbyone** [comment]
I am aware of #35, but it doesn't appear to answer the core question here

**Comment by piyueh** [comment]
If you're using Arch Linux, you can try this AUR package: https://aur.archlinux.org/packages/python-imaplib2-git/
I just packaged it. PR4, PR6, and PR15 at https://github.com/jazzband/imaplib2 were applied to the AUR package. I also bumped the version to 3.6 (according to the hard-coded number in `imaplib2.py3`, the Python 3 version of `imaplib2` is currently at v3.6).

If you are not using Arch, then just pull the [jazzband/imaplib2](https://github.com/jazzband/imaplib2) repo and download the patches from the abovementioned AUR page. Then

1. apply `pr4_pr6_pr15.patch`
2. apply `version.patch`
3. rename `imaplib2/imaplib2.py3` to `imaplib2/imaplib2.py` (and discard the original `imaplib2/imaplib2.py`)
4. run `python setup.py install`

If everything works, when you do `pip show imaplib2`, the version should show it's 3.6. This version is working with the **_offlineimap 3_** on my system, though I don't really use **_offlineimap_** much.

**Comment by offbyone** [comment]
I'm not. I'm using macos.

**Comment by thekix** [comment]
Hi,

we were working with imaplib2. This library was moved to jazzband/imaplib2 (https://github.com/jazzband/imaplib2) and it is maintained again.

Please again with pip (example in Windows):

```
$ pip install 'imaplib2>=3.5'
Collecting imaplib2>=3.5
  Using cached imaplib2-3.6-py3-none-any.whl (25 kB)
Installing collected packages: imaplib2
Successfully installed imaplib2-3.6
```

And then:

```
C:\Users\kix\src\offlineimap3>python
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import imaplib2
>>> print(imaplib2.version())
3.06
>>> print(imaplib2.__version__)
3.06
>>>
```
