### ISSUE TITLE
exception on mailboxes with spaces in name

### ISSUE THREAD

**Issue by patrickdepinguin** [OfflineIMAP/offlineimap3#4]
#### General informations

- system/distribution (with version): Gentoo Linux -- latest 2020-09-26
- offlineimap version (`offlineimap -V`): git commit 8dca9168ec9ac7cd58910cc64266726a962285e9       (output printed: offlineimap v7.3.0, imaplib2 v3.05, Python v3.7.8, OpenSSL 1.1.1g  21 Apr 2020)
- Python version: 3.7
- server name or domain: /
- CLI options: none

#### Logs, error

```
Folder foo bar [acc: my-account]:
 ERROR: ERROR in syncfolder for my-account folder foo bar: Traceback (most recent call last):
  File "/home/user/repo/offlineimap3/offlineimap/accounts.py", line 651, in syncfolder
    check_uid_validity()
  File "/home/user/repo/offlineimap3/offlineimap/accounts.py", line 512, in check_uid_validity
    if not remotefolder.check_uidvalidity():
  File "/home/user/repo/offlineimap3/offlineimap/folder/Base.py", line 227, in check_uidvalidity
    return self.get_saveduidvalidity() == self.get_uidvalidity()
  File "/home/user/repo/offlineimap3/offlineimap/folder/IMAP.py", line 138, in get_uidvalidity
    self.__selectro(imapobj)
  File "/home/user/repo/offlineimap3/offlineimap/folder/IMAP.py", line 86, in __selectro
    imapobj.select(self.getfullIMAPname(), force=force)
  File "/home/user/repo/offlineimap3/offlineimap/imaplibutil.py", line 51, in select
    result = super(UsefulIMAPMixIn, self).select(mailbox, readonly)
  File "/home/user/repo/offlineimap3/venv/lib/python3.7/site-packages/imaplib2.py", line 1053, in select
    self._deliver_exc(self.error, '%s command error: %s %s. Data: %.100s' % (name, typ, dat, mailbox), kw)
  File "/home/user/repo/offlineimap3/venv/lib/python3.7/site-packages/imaplib2.py", line 1467, in _deliver_exc
    raise exc(dat)
imaplib2.IMAP4.error: SELECT command error: BAD [b'Command Argument Error. 12']. Data: foo bar

  SELECT command error: BAD [b'Command Argument Error. 12']. Data: foo bar

```

#### Steps to reproduce the error

- This error occurs always, on mailboxes that have a space in the name, like 'foo bar'.

I can fix/workaround the problem by changing imaplib2.py as follows:
```
--- venv/lib/python3.7/site-packages/imaplib2.py.orig	2020-09-28 11:05:07.235030053 +0200
+++ venv/lib/python3.7/site-packages/imaplib2.py	2020-09-28 11:05:13.925078829 +0200
@@ -1043,7 +1043,7 @@
         else:
             name = 'SELECT'
         try:
-            rqb = self._command(name, mailbox)
+            rqb = self._command(name, self._quote(mailbox))
             typ, dat = rqb.get_response('command: %s => %%s' % rqb.name)
             if typ != 'OK':
                 if self.state == SELECTED:
```

i.e. quoting the mailbox name, as specified by the IMAP4 RFC.

However, the above fix does not seem complete (there may be other places where the same quoting should happen).
Moreover, when using offlineimap for Python 2 (version: "offlineimap v7.3.3, imaplib2 v2.101 (bundled), Python v2.7.18, OpenSSL 1.1.1g  21 Apr 2020" ), this problem does not occur.

**Comment by thekix** [comment]
Hello,

thanks @patrickdepinguin 

I was checking the RFC and yes, we need quote it. We can quote it in the offlineimap code, not in the imaplib2.py file. I am working on it.

Regards,
kix

**Comment by thekix** [comment]
Hello,

I included a new patch solving this issue. Please, tell me if all is fine.

Regards,
kix

**Comment by patrickdepinguin** [comment]
Gracias, I reverted my local change in imaplib and updated to your fix, no problem in fetching data from folders with spaces.
