### ISSUE TITLE
traceback when using "remotepassfile" option

### ISSUE THREAD

**Issue by sudipm-mukherjee** [OfflineIMAP/offlineimap3#40]
#### General informations

- system/distribution (with version): Debian unstable
- offlineimap version (`offlineimap -V`): offlineimap v7.3.0, imaplib2 v3.05, Python v3.9.1+, OpenSSL 1.1.1i  8 Dec 2020
- offlineimap Debian version: 0.0~git20210105.00d395b+dfsg-2
- Debian bug: https://bugs.debian.org/981063

#### Configuration file offlineimaprc

Use `remotepassfile` in the offlineimaprc.

#### Logs, error

$ offlineimap -o -f test
OfflineIMAP 7.3.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v3.05, Python v3.9.1+, OpenSSL 1.1.1i  8 Dec 2020
Account sync Gmail:
 *** Processing account Gmail
 Establishing connection to imap.gmail.com:993 (Gmail-Remote)
 ERROR: While attempting to sync account 'Gmail'
  sequence item 2: expected str instance, bytes found
 *** Finished account 'Gmail' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: While attempting to sync account 'Gmail'
  sequence item 2: expected str instance, bytes found

Traceback:
  File "/usr/share/offlineimap3/offlineimap/accounts.py", line 298, in syncrunner
    self.__sync()
  File "/usr/share/offlineimap3/offlineimap/accounts.py", line 374, in __sync
    remoterepos.getfolders()
  File "/usr/share/offlineimap3/offlineimap/repository/IMAP.py", line 648, in getfolders
    imapobj = self.imapserver.acquireconnection()
  File "/usr/share/offlineimap3/offlineimap/imapserver.py", line 592, in acquireconnection
    self.__authn_helper(imapobj)
  File "/usr/share/offlineimap3/offlineimap/imapserver.py", line 449, in __authn_helper
    if func(imapobj):
  File "/usr/share/offlineimap3/offlineimap/imapserver.py", line 375, in __authn_plain
    imapobj.authenticate('PLAIN', self.__plainhandler)
  File "/usr/lib/python3/dist-packages/imaplib2.py", line 691, in authenticate
    typ, dat = self._simple_command('AUTHENTICATE', mechanism.upper())
  File "/usr/lib/python3/dist-packages/imaplib2.py", line 1684, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/lib/python3/dist-packages/imaplib2.py", line 1404, in _command
    literal = literator(data, rqb)
  File "/usr/lib/python3/dist-packages/imaplib2.py", line 2247, in process
    ret = self.mech(self.decode(data))
  File "/usr/share/offlineimap3/offlineimap/imapserver.py", line 217, in __plainhandler
    retval = NULL.join((authz, authc, passwd))

#### Steps to reproduce the error

Use `remotepassfile` in the offlineimaprc.

**Comment by sudipm-mukherjee** [comment]
The attached patch in the Debian bug fixes the issue for me and also for the reporter.  Also copied here for your convenience.

```
From 4f5d97e91e6c0b732120a1c02b6e728068c77e23 Mon Sep 17 00:00:00 2001
From: Vagrant Cascadian <vagrant@debian.org>
Date: Mon, 25 Jan 2021 12:44:06 -0800
Subject: [PATCH] Do not encode password in UTF-8 when reading from
 "remotepassfile".

https://bugs.debian.org/981063

---
 offlineimap/repository/IMAP.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/offlineimap/repository/IMAP.py b/offlineimap/repository/IMAP.py
index b732243..6fb7f4a 100644
--- a/offlineimap/repository/IMAP.py
+++ b/offlineimap/repository/IMAP.py
@@ -590,7 +590,7 @@ class IMAPRepository(BaseRepository):
                              encoding='utf-8')
             password = file_desc.readline().strip()
             file_desc.close()
-            return password.encode('UTF-8')
+            return password
         # 4. Read password from ~/.netrc.
         try:
             netrcentry = netrc.netrc().authenticators(self.gethost())
--
2.29.2
```

**Comment by g0hl1n** [comment]
Same issue happens on my system. The patch provided by @sudipm-mukherjee which removes the UTF-8 encoding from the remotepassfile fixes the issue for me too.

Although I'm not sure this is the root cause :thinking: Unfortunately currently I have no time for doing more work on this issue :disappointed:
