### ISSUE TITLE
Omitting sslcacertfile in favor of cert_fingerprint is not working

### ISSUE THREAD

**Issue by dgoulet** [OfflineIMAP/offlineimap3#41]
#### General informations

- system/distribution (with version): Ubuntu 21.04
- offlineimap version (`offlineimap -V`): offlineimap v7.3.0, imaplib2 v3.05, Python v3.9.1+, OpenSSL 1.1.1f  31 Mar 2020
- Python version: Python 3.9.1+
- server name or domain: See config file.
- CLI options: 

#### Configuration file offlineimaprc

This is a configuration to connect to Riseup.net email server over tor using their .onion address. They serve an HTTPs certificate that does **not** contain the onion address cname and thus validation fails without a matching domain name.

```
[Account riseup.net]
localrepository = riseup.net-local
remoterepository = riseup.net-remote
autorefresh = 1
quick = 20
socktimeout = 20

[Repository riseup.net-local]
type = Maildir
localfolders = <PATH>

[Repository riseup.net-remote]
type = IMAP
remotehost = 5gdvpfoh6kb2iqbizb37lzk2ddzrwa47m6rpdueg2m656fovmbhoptqd.onion
remoteport = 993
cert_fingerprint = af121b43c05056f1103461eb50d7ba45193a3f97
sslcacertfile =
ssl = yes
holdconnectionopen = yes
remoteuser = <USER>
remotepasseval = <PASSWORD>
idlefolders = ['INBOX']
folderfilter = lambda foldername: foldername in ['INBOX', 'Sent', 'Trash', 'Drafts']
```

#### Logs, error

```
ERROR: While attempting to sync account 'riseup.net' ('CA Cert verifying failed:  no matching domain name found in certificate',)
```

#### Steps to reproduce the error

Simply run: `torsocks offlineimap -a riseup.net`

Now I believe I found the problem. In `repository/IMAP.py`, the `getsslcacertfile()` is responsible to look for the `sslcacertfile` config value which if omitted is thus `None` and the fallback goes onto the CA system file path which is good. By default, it is good to always attempt to validate.

However, in this very specific case described in this ticket, the validation must be done through `cert_fingerprint` and thus omitting it or setting it to an empty string should be enough to ignore it but current code does not:

```
        conf_sslacertfile = self.getconf('sslcacertfile', None)
        if conf_sslacertfile == "OS-DEFAULT" or \
                conf_sslacertfile is None or \
                conf_sslacertfile == '':
            cacertfile = get_os_sslcertfile()
```

Both the empty string and the `None` value fallback to the CA system path and thus we never fallback to `cert_fingerprint`.

Either `conf_sslacertfile == ''` is removed or having a `cert_fingerprint` is enough to bypass this CA check if `sslcacertfile` is `None` or empty string? Or maybe a more explicit approach would be to make the user explicitly disable CA validation through an option... Unclear what is best from my perspective.

Note that the above used to work with offlineimap2 for which I have been using this for years.

**Comment by sudipm-mukherjee** [comment]
I have also faced the similar issue with only `cert_fingerprint` used in offlineimaprc file.
Also reported by another Debian user at `https://bugs.debian.org/981338`

**Comment by sudipm-mukherjee** [comment]
Digging into the changes for offlineimap3, it has been caused by a4863b2f04adf25b9989bafbb9df21ea8b98a674 and looking at the issue at https://github.com/OfflineIMAP/offlineimap3/issues/14, it seems like an improvement for new users. But this breaks the setup of lots of old users which I dont think is a desirable consequences.

**Comment by duritong** [comment]
https://github.com/OfflineIMAP/offlineimap3/pull/66 gives something mergeable
