### ISSUE TITLE
Error when creating folders with spaces on GMail's IMAP server

### ISSUE THREAD

**Issue by piyueh** [OfflineIMAP/offlineimap3#58]
#### General informations

- system/distribution (with version):  Arch Linux, kernel 5.11.1-arch1-1
- offlineimap version (`offlineimap -V`): 
    - from `offlineimap -V`: offlineimap v7.3.0, imaplib2 v3.06, Python v3.9.2, OpenSSL 1.1.1j  16 Feb 2021
    - it's actually offlineimap3 commit 1e7ef9e with patches from #55 and changes according to jazzband/imaplib2#15)
- Python version: 3.9
- server name or domain: gmail 
- CLI options: `-o -a test -c ${HOME}/config.test`

#### Configuration file offlineimaprc

```
[general]
metadata = $HOME/offlineimap_tmp
accounts = test

[Account test]
localrepository = test-local
remoterepository = test-remote

[Repository test-local]
type = GmailMaildir
localfolders = $HOME/offlineimap_test
sep = .

[Repository test-remote]
type = Gmail
remoteuser = <account>
auth_mechanisms = XOAUTH2
oauth2_client_id = <id>
oauth2_client_secret = <secret>
oauth2_access_token = <token>
folderfilter = lambda folder: folder  == "Test ABC"
```

#### Logs, error

```python
OfflineIMAP 7.3.0
  Licensed under the GNU GPL v2 or any later version (with an OpenSSL exception)
imaplib2 v3.06, Python v3.9.2, OpenSSL 1.1.1j  16 Feb 2021
Account sync test:
 *** Processing account test
 Establishing connection to imap.gmail.com:993 (test-remote)
 Creating folder Test ABC[test-remote]
 ERROR: While attempting to sync account 'test'
  CREATE command error: BAD [b'Could not parse command']. Data: b'HENK8 CREATE Test ABC\r\n'
 *** Finished account 'test' in 0:00
ERROR: Exceptions occurred during the run!
ERROR: While attempting to sync account 'test'
  CREATE command error: BAD [b'Could not parse command']. Data: b'HENK8 CREATE Test ABC\r\n'

Traceback:
  File "/usr/lib/python3.9/site-packages/offlineimap/accounts.py", line 298, in syncrunner
    self.__sync()
  File "/usr/lib/python3.9/site-packages/offlineimap/accounts.py", line 377, in __sync
    remoterepos.sync_folder_structure(localrepos, statusrepos)
  File "/usr/lib/python3.9/site-packages/offlineimap/repository/Base.py", line 349, in sync_folder_structure
    remote_repo.makefolder(remote_name)
  File "/usr/lib/python3.9/site-packages/offlineimap/repository/IMAP.py", line 816, in makefolder
    self.makefolder_single(folder_path)
  File "/usr/lib/python3.9/site-packages/offlineimap/repository/IMAP.py", line 839, in makefolder_single
    result = imapobj.create(foldername)
  File "/usr/lib/python3.9/site-packages/imaplib2/imaplib2.py", line 767, in create
    return self._simple_command('CREATE', mailbox, **kw)
  File "/usr/lib/python3.9/site-packages/imaplib2/imaplib2.py", line 1705, in _simple_command
    return self._command_complete(self._command(name, *args), kw)
  File "/usr/lib/python3.9/site-packages/imaplib2/imaplib2.py", line 1452, in _command_complete
    raise self.error('%s command error: %s %s. Data: %.100s' % (rqb.name, typ, dat, rqb.data))
```

##### Step 1: create a test maildir

```
$ mkdir -p \
    $HOME/offlineimap_test/Test\ ABC/cur
    $HOME/offlineimap_test/Test\ ABC/new
    $HOME/offlineimap_test/Test\ ABC/tmp
```

##### Step 2: run offlineimap

```
$ offlineimap -o -a test -c ${HOME}/config.test
```

#### Description

When `offlineimap` tried to create a folder on GMail's IMAP server, and when that folder had spaces in its folder name, the creation failed.

#### Temporary solution

I have a workaround on my machine: wrapping folder names with double-quotes. However, I believe this workaround is not robust. If a folder name already has double-quotes in its name, I don't know if this workaround is going to work (though I doubt how many people have quotation marks in their folders' names). Here's my workaround:

Replace [line 839 in `repository/IMAP.py`](https://github.com/OfflineIMAP/offlineimap3/blob/1e7ef9e7e6952f5d29ef0f5c25fd062798de55f3/offlineimap/repository/IMAP.py#L839):
https://github.com/OfflineIMAP/offlineimap3/blob/1e7ef9e7e6952f5d29ef0f5c25fd062798de55f3/offlineimap/repository/IMAP.py#L839

with
```
result = imapobj.create("\"{}\"".format(foldername))
```

**Comment by nicolas33** [comment]
This trick might be ok in usual python code. However, this requires to check how it's translated by imaplib2 and if this is IMAP-compliant.

**Comment by thekix** [comment]
Hi @piyueh !

please, could you try now?

Thanks a lot,
Best regards,
kix

**Comment by piyueh** [comment]
@thekix Yes, it works for me now! Thanks!
