### ISSUE TITLE
offlineimap error upon process start - new installation of offlineimap(3) on debian 11

### ISSUE THREAD

**Issue by vale46** [OfflineIMAP/offlineimap3#74]
#### General informations

- system/distribution (with version): ```Debian GNU/Linux 11 (bullseye)```
- offlineimap version (`offlineimap -V`): ```offlineimap v7.3.0, imaplib2 v3.05, Python v3.9.2, OpenSSL 1.1.1k  25 Mar 2021```
- offlineimap pkgs (thru ```dpkg-query -l```): 
```
ii  offlineimap                           7.3.3+dfsg1-1+0.0\~git20210225.1e7ef9e+dfsg-4 all          transitional package
ii  offlineimap3                          0.0~git20210225.1e7ef9e+dfsg-4               all          IMAP/Maildir synchronization and reader support
ii  python3-imaplib2                      2.57-5.2                                     all          Threaded Python IMAP4 client (Python 3)
```

- Python version: ```3.9.2```
- server name or domain: ```https://accounts.google.com/o/oauth2/token```
- CLI options: ```none```

#### Configuration file offlineimaprc

```
[general]
metadata = ~/.offlineimap
accounts = gmail
maxsyncaccounts = 1
pythonfile = $XDG_CONFIG_HOME/offlineimap/.offlineimap.py
socktimeout = 60

[Account gmail]
localrepository = LocalGmail
remoterepository = RemoteGmail
quick = 10
maxsize = 2000000
maxage = 2015-04-01
#maxage = 10
postsynchook = mu index --maildir ~/mails

[Repository LocalGmail]
type = Maildir
localfolders = ~/mails/gmail

[Repository RemoteGmail]
type = Gmail
maxconnections = 2
remoteuser = xxx@gmail.com

oauth2_request_url = https://accounts.google.com/o/oauth2/token
oauth2_client_id_eval = mailpasswd("gmail/oauth2_client_id")
oauth2_client_secret_eval = mailpasswd("gmail/oauth2_client_secret")
oauth2_refresh_token_eval = mailpasswd("gmail/oauth2_refresh_token")

folderfilter = lambda foldername: foldername not in ['[Gmail]/All Mail', '[Gmail]/Important']
sslcacertfile = /etc/ssl/certs/ca-certificates.crt

```

#### pythonfile (if any)

```
import os
import subprocess

def mailpasswd(acct):
  # acct = os.path.basename(acct)
  path = "/home/xxx/.password-store/%s.gpg" % acct
  args = ["gpg", "--use-agent", "--quiet", "--batch", "-d", path]
  try:
    return subprocess.check_output(args).strip()
  except subprocess.CalledProcessError:
    return ""

def prime_gpg_agent():
  ret = False
  i = 1
  while not ret:
    ret = (mailpasswd("generic/prime") == "prime")
    if i > 2:
      from offlineimap.ui import getglobalui
      sys.stderr.write("Error reading in passwords. Terminating.\n")
      getglobalui().terminate()
    i += 1
  return ret

prime_gpg_agent()
```

#### Logs, error

```
Traceback (most recent call last):
  File "/usr/bin/offlineimap", line 22, in <module>
    oi.run()
  File "/usr/share/offlineimap3/offlineimap/init.py", line 86, in run
    options, args = self.__parse_cmd_options()
  File "/usr/share/offlineimap3/offlineimap/init.py", line 262, in __parse_cmd_options
    config.set_if_not_exists('general', 'dry-run', 'False')
  File "/usr/share/offlineimap3/offlineimap/CustomConfig.py", line 127, in set_if_not_exists
    self.set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'general'
```

#### Steps to reproduce the error
- ```offlineimap``` on command line, w/o any options.

#### Other comments 
The error happens very early on after launching offlineimap process; from what I can tell the parser is not able unable to find the [general] section in offlineimap config file. My setup appears to be correct, but happy to get feedback.

Also, would be very helpful to get confirmation if the pythonfile script is Python 3 compatible.

Thank You in advance!

**Comment by piyueh** [comment]
A wild guess: it looks like `offlineimap` was reading a wrong config file, and that wrong config file does not have a `[general]` section. Do you still get the error if you manually specify the path of the configuration file? (In the terminal, execute `offlineimap -c  <path to your config file>`).

**Comment by vale46** [comment]
thanks! that helps fix the initial read config file error - any idea why the config file is not being picked up when invoking offlineimap since its template mentions that it can be placed here: ```$XDG_CONFIG_HOME/offlineimap/config/.offlineimaprc``` which is the location in my setup.

**Comment by piyueh** [comment]
I think it means the configuration file name should be `$XDG_CONFIG_HOME/offlineimap/config`, not `$XDG_CONFIG_HOME/offlineimap/config/.offlineimaprc`.

**Comment by vale46** [comment]
thanks for your clarification! I got thru the initial error, but the python script throws an error during authentication, which I'm trying to understand/debug. I'll close this issue.
